### ISSUE TITLE
MEXP alive

### ISSUE THREAD

**Issue by denser** [AThomsen/mexp#2]
Hi. I want to try to resurrect mexp )) Want to adopt it to windows 10(profiles etc)
I need some ancient components for delphi 7 - could you share them?

**Comment by AThomsen** [comment]
Hi :-)

Sounds great! I'll be glad to help in any way possible.

What exactly do you need?

**Comment by denser** [comment]
Hi)) I dont touch delphi for ages)) Last time about 10-15 years...long time..dam..
Anyway) I work on windows 10 and try to download and build mexp)) 

I am almost lost. Find some portable delphi..IDK)) if it right or i am wrong)
Trying to set up components - treeview only found, other cant. too old stuff i think. 

Do you have ready-to-use stuff?
May be i should rewrite it to modern Visual Studio or something...

In mean time MEXP helps me work as DJ ))) And even find some rare music on my HDD over 300 GB files ...was a time, yeah. 

So i have some warm wish to make MEXP live again)) and usae my collection.

For now i made it works , but MEXP dont know about profiles and try to use winamp Program FIles folder.
Wanna just fix it, but when started - i wonder that i need more skills and old components...

Help me start pls :)

**Comment by denser** [comment]
rip. was cool in 200X years to use as DJ app :)
